/* Renoweet Bookkeeping UI v4.4 — one accounting engine, simple daily workflow. */
(()=>{
'use strict';
const A=window.RenoweetAccounting;if(!A)return;
let lineDraft=[];
const byId=id=>document.getElementById(id);
const html=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]));
const money=v=>euro.format(A.num(v));
const invoiceLogoSrc=()=>document.querySelector('header .brand img')?.getAttribute('src')||'';
const statusLabel={draft:'Draft',issued:'Open',partially_paid:'Partially paid',paid:'Paid',overdue:'Overdue',credited:'Credited',cancelled:'Cancelled'};

function ensureV44Data(){
  A.normalizeBookkeeping(data);data.control=data.control||{};data.control.AccountingSchema='4.4';
  for(const r of data.invoices)if(!r['Record ID'])r['Record ID']=r._rid||A.makeId('INV');
  for(const r of [...data.expenses,...data.fuel,...data.auto])if(!r['Record ID'])r['Record ID']=r._rid||A.makeId('EXP');
}
function activePeriod(){
  const st=window.renoweetDriveBK?.state,y=Number(st?.year)||new Date().getFullYear(),q=Number(st?.selectedQuarter)||Math.floor(new Date().getMonth()/3)+1,start=new Date(y,(q-1)*3,1),end=new Date(y,q*3,0);
  return {year:y,quarter:q,start,end,label:`Q${q} ${y}`};
}
function yearPeriod(){const y=activePeriod().year;return {year:y,start:new Date(y,0,1),end:new Date(y,11,31),label:String(y)}}
function stateFor(r){return A.invoiceState(r,data.payments,data.creditNotes)}
function rowRef(id){return data.invoices.find(r=>A.invoiceId(r)===id)}
function expenseSources(){return [...data.expenses.map((r,index)=>({r,type:'General',index})),...data.fuel.map((r,index)=>({r,type:'Fuel',index})),...data.auto.map((r,index)=>({r,type:'Automobile',index}))]}
function visibleStatus(r){return stateFor(r).status}

function reportSummaryCard(label,value,tone=''){return `<div class="mini ${tone}"><span>${html(label)}</span><b>${html(value)}</b></div>`}
function reportSectionTitle(title,detail=''){return `<div class="section-title"><strong>${html(title)}</strong>${detail?`<small>${html(detail)}</small>`:''}</div>`}
function reportStatusPill(status){return `<span class="status-pill ${html(status)}">${html(statusLabel[status]||status)}</span>`}
function reportTable(headers,widths,body,footer=''){
  return `<div class="table-shell"><table><colgroup>${widths.map(w=>`<col style="width:${w}">`).join('')}</colgroup><thead><tr>${headers.map((h,i)=>`<th class="${h.money?'money':h.center?'center':''}">${html(h.label||h)}</th>`).join('')}</tr></thead><tbody>${body}</tbody>${footer?`<tfoot>${footer}</tfoot>`:''}</table></div>`;
}
function invoiceDescription(r){const lines=A.parseLines(r).map(l=>A.text(l.description)).filter(Boolean);return lines.join(' • ')||A.text(r['Work description'])||'—'}
function invoicePrintReport(){
  const p=activePeriod(),period=A.periodRows(data,p),rows=[...period.invoices].sort((a,b)=>A.iso(a.Date).localeCompare(A.iso(b.Date))||A.text(a['Invoice #']).localeCompare(A.text(b['Invoice #']))),vat=A.vatReport(data,p),cash=A.cashReport(data,p);
  const issued=rows.filter(A.isIssued),outstanding=A.round2(rows.reduce((sum,r)=>sum+stateFor(r).outstanding,0)),counts={draft:0,issued:0,partially_paid:0,paid:0,overdue:0,credited:0,cancelled:0};
  rows.forEach(r=>{const s=visibleStatus(r);counts[s]=(counts[s]||0)+1});
  const invoiceTotals=issued.reduce((a,r)=>{const t=A.invoiceTotals(r);a.net+=t.net;a.vat+=t.vat;a.gross+=t.gross;return a},{net:0,vat:0,gross:0}),paid=A.round2(rows.reduce((sum,r)=>sum+stateFor(r).paid,0));
  const bodyRows=rows.map(r=>{const t=A.invoiceTotals(r),s=stateFor(r);return `<tr><td><b>${html(r['Invoice #']||'Draft')}</b></td><td>${html(A.iso(r['Invoice date']||r.Date)||'—')}</td><td>${html(A.iso(r['Due date'])||'—')}</td><td>${html(r.Customer||'—')}</td><td>${html(invoiceDescription(r))}</td><td class="money">${money(t.net)}</td><td class="money">${money(t.vat)}</td><td class="money">${money(t.gross)}</td><td class="money">${money(s.paid)}</td><td class="money">${money(s.outstanding)}</td><td class="center">${reportStatusPill(s.status)}</td></tr>`}).join('')||'<tr><td colspan="11" class="center muted">No invoices in this period.</td></tr>';
  const footer=issued.length?`<tr><td colspan="5">Issued invoice totals</td><td class="money">${money(invoiceTotals.net)}</td><td class="money">${money(invoiceTotals.vat)}</td><td class="money">${money(invoiceTotals.gross)}</td><td class="money">${money(paid)}</td><td class="money">${money(outstanding)}</td><td></td></tr>`:'';
  const statusText=`Paid ${counts.paid||0} • Open ${counts.issued||0} • Partial ${counts.partially_paid||0} • Overdue ${counts.overdue||0} • Draft ${counts.draft||0} • Credited ${counts.credited||0} • Cancelled ${counts.cancelled||0}`;
  const creditNote=period.creditNotes.length?` Top summaries include ${period.creditNotes.length} credit note${period.creditNotes.length===1?'':'s'}; the table retains each original invoice document and shows its current payment position.`:'';
  const body=`<div class="summary">${reportSummaryCard('All invoice records',String(rows.length))}${reportSummaryCard('Issued gross',money(vat.salesGross))}${reportSummaryCard('Revenue ex VAT',money(vat.salesNet))}${reportSummaryCard('Output VAT',money(vat.outputVat))}${reportSummaryCard('Cash received',money(cash.cashIn))}${reportSummaryCard('Outstanding',money(outstanding),outstanding>0?'warn':'')}</div><div class="note"><b>Status overview:</b> ${html(statusText)}.${html(creditNote)}</div>${reportSectionTitle('Complete invoice register',`${rows.length} record${rows.length===1?'':'s'} • ${p.label}`)}${reportTable([{label:'Invoice'},{label:'Invoice date'},{label:'Due date'},{label:'Customer'},{label:'Description'},{label:'Net',money:true},{label:'VAT',money:true},{label:'Gross',money:true},{label:'Paid',money:true},{label:'Outstanding',money:true},{label:'Status',center:true}],['7%','7%','7%','10%','17%','8%','7%','8%','8%','8%','13%'],bodyRows,footer)}`;
  window.printHtmlReport('Invoice register',p.label,body,{landscape:true});
}
function expensePrintReport(){
  const p=activePeriod(),rows=[...A.periodRows(data,p).expenses].sort((a,b)=>A.iso(a['Document date']||a.Date).localeCompare(A.iso(b['Document date']||b.Date))||A.text(a.Supplier).localeCompare(A.text(b.Supplier))),totals=rows.reduce((a,r)=>{const f=A.expenseFacts(r);a.gross+=f.gross;a.invoiceVat+=f.invoiceVat;a.deductibleVat+=f.deductibleVat;a.cost+=f.deductibleCost;if(!A.text(r['Receipt/File']))a.missing+=1;return a},{gross:0,invoiceVat:0,deductibleVat:0,cost:0,missing:0}),categories=new Map();
  rows.forEach(r=>{const f=A.expenseFacts(r),category=A.text(r.Category||r._ledgerCategory||r['Legacy type'])||'Other',entry=categories.get(category)||{count:0,gross:0,vat:0,cost:0};entry.count+=1;entry.gross+=f.gross;entry.vat+=f.deductibleVat;entry.cost+=f.deductibleCost;categories.set(category,entry)});
  const categoryRows=[...categories.entries()].sort((a,b)=>b[1].cost-a[1].cost).map(([category,x])=>`<tr><td>${html(category)}</td><td class="center">${x.count}</td><td class="money">${money(x.gross)}</td><td class="money">${money(x.vat)}</td><td class="money">${money(x.cost)}</td></tr>`).join('')||'<tr><td colspan="5" class="center muted">No expenses in this period.</td></tr>';
  const categoryFooter=rows.length?`<tr><td>Total</td><td class="center">${rows.length}</td><td class="money">${money(totals.gross)}</td><td class="money">${money(totals.deductibleVat)}</td><td class="money">${money(totals.cost)}</td></tr>`:'';
  const detailRows=rows.map(r=>{const f=A.expenseFacts(r),proof=A.text(r['Receipt/File']);return `<tr><td>${html(A.iso(r['Document date']||r.Date)||'—')}</td><td>${html(r.Supplier||'—')}</td><td>${html(r.Category||r._ledgerCategory||r['Legacy type']||'Other')}</td><td>${html(r.Description||'—')}</td><td class="money">${money(f.gross)}</td><td class="money">${money(f.invoiceVat)}</td><td class="money">${money(f.deductibleVat)}</td><td class="center">${html(`${f.vatPct}%`)}</td><td class="money">${money(f.deductibleCost)}</td><td class="center">${html(r['Payment status']||'Paid')}</td><td class="center">${proof?'<span class="status-pill paid">Linked</span>':'<span class="status-pill overdue">Missing</span>'}</td></tr>`}).join('')||'<tr><td colspan="11" class="center muted">No expenses in this period.</td></tr>';
  const detailFooter=rows.length?`<tr><td colspan="4">All expense totals</td><td class="money">${money(totals.gross)}</td><td class="money">${money(totals.invoiceVat)}</td><td class="money">${money(totals.deductibleVat)}</td><td></td><td class="money">${money(totals.cost)}</td><td colspan="2"></td></tr>`:'';
  const body=`<div class="summary">${reportSummaryCard('All expenses',String(rows.length))}${reportSummaryCard('Gross spending',money(totals.gross))}${reportSummaryCard('Invoice VAT',money(totals.invoiceVat))}${reportSummaryCard('Deductible VAT',money(totals.deductibleVat))}${reportSummaryCard('Deductible cost',money(totals.cost))}${reportSummaryCard('Missing proofs',String(totals.missing),totals.missing?'alert':'')}</div>${reportSectionTitle('Summary by category',`${categories.size} categor${categories.size===1?'y':'ies'}`)}${reportTable([{label:'Category'},{label:'Entries',center:true},{label:'Gross',money:true},{label:'Deductible VAT',money:true},{label:'Deductible cost',money:true}],['40%','10%','17%','16%','17%'],categoryRows,categoryFooter)}<div class="note">Deductible VAT uses the recorded VAT-deduction percentage. Deductible cost uses the recorded income-tax percentage and includes any non-deductible VAT in the cost base.</div>${reportSectionTitle('Complete expense register',`${rows.length} record${rows.length===1?'':'s'} • ${p.label}`)}${reportTable([{label:'Date'},{label:'Supplier'},{label:'Category'},{label:'Description'},{label:'Gross',money:true},{label:'Invoice VAT',money:true},{label:'Deductible VAT',money:true},{label:'VAT deduct.',center:true},{label:'Deductible cost',money:true},{label:'Payment',center:true},{label:'Proof',center:true}],['7%','10%','9%','15%','8%','8%','8%','7%','9%','9%','10%'],detailRows,detailFooter)}`;
  window.printHtmlReport('Business expense register',p.label,body,{landscape:true});
}
window.printInvoices=invoicePrintReport;
window.printExpenses=expensePrintReport;

function injectInvoiceEditor(){
  const modal=byId('invoiceModal')?.querySelector('.modal-card');if(!modal||byId('v44InvoiceLines'))return;
  for(const id of ['invGross','invParking','invOther','invVatRate','invCustomVat']){const el=byId(id);if(el?.closest('.field'))el.closest('.field').style.display='none'}
  const note=modal.querySelector('.hint');if(note)note.textContent='Invoice totals are calculated from the line items below. Issue the invoice to allocate its permanent number.';
  const box=document.createElement('div');box.id='v44InvoiceLines';box.className='v44-section';box.innerHTML=`<div class="v44-section-head"><div><div class="v44-eyebrow">Invoice lines</div><h3>Work, materials and recharges</h3></div><button type="button" class="secondary" id="v44AddLine">+ Add line</button></div><div class="v44-line-head"><span>Description</span><span>Qty</span><span>Net / unit</span><span>VAT treatment</span><span></span></div><div id="v44LineRows"></div><div class="v44-line-total"><span>Net <b id="v44LineNet">€0.00</b></span><span>VAT <b id="v44LineVat">€0.00</b></span><span>Total <strong id="v44LineGross">€0.00</strong></span></div>`;
  note?.before(box);byId('v44AddLine').onclick=()=>{lineDraft.push({id:A.makeId('LIN'),description:'',quantity:1,unitNet:0,vatRate:21,vatTreatment:'NL_HIGH'});renderLineEditor()};
  byId('v44LineRows').addEventListener('input',readLineEditor);byId('v44LineRows').addEventListener('change',readLineEditor);
  const supply=document.createElement('div');supply.className='field';supply.innerHTML='<label>Supply date</label><input id="invSupplyDate" type="date">';byId('invDue')?.closest('.field')?.before(supply);
  const status=byId('invStatus');status.innerHTML='<option value="Draft">Draft</option><option value="Open">Issued / open</option><option value="Partially paid">Partially paid</option><option value="Paid">Paid</option><option value="Overdue">Overdue</option><option value="Credited">Credited</option><option value="Cancelled">Cancelled</option>';
}
function renderLineEditor(){
  const host=byId('v44LineRows');if(!host)return;host.innerHTML=lineDraft.map((l,i)=>`<div class="v44-line-row" data-i="${i}"><input class="v44-desc" data-k="description" value="${html(l.description)}" placeholder="Work or material"><input data-k="quantity" type="number" min="0.01" step="0.01" value="${l.quantity||1}"><input data-k="unitNet" type="number" step="0.01" min="0" value="${A.num(l.unitNet)}"><select data-k="vatRate"><option value="21" ${A.num(l.vatRate)===21?'selected':''}>21% NL</option><option value="9" ${A.num(l.vatRate)===9?'selected':''}>9% NL</option><option value="0" ${A.num(l.vatRate)===0?'selected':''}>0% / exempt</option></select><button type="button" class="danger v44-icon-btn" data-remove="${i}" aria-label="Remove line">×</button></div>`).join('');
  host.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(lineDraft.length>1){lineDraft.splice(Number(b.dataset.remove),1);renderLineEditor()}});syncInvoiceTotals();
}
function readLineEditor(){
  document.querySelectorAll('#v44LineRows .v44-line-row').forEach(row=>{const i=Number(row.dataset.i),l=lineDraft[i];row.querySelectorAll('[data-k]').forEach(el=>{const k=el.dataset.k;l[k]=['quantity','unitNet','vatRate'].includes(k)?A.num(el.value):el.value});l.vatTreatment=l.vatRate===21?'NL_HIGH':l.vatRate===9?'NL_LOW':'NL_ZERO'});syncInvoiceTotals();
}
function draftTotals(){return lineDraft.reduce((a,l)=>{const t=A.lineTotals(l);a.net+=t.net;a.vat+=t.vat;return a},{net:0,vat:0})}
function syncInvoiceTotals(){const t=draftTotals(),g=A.round2(t.net+t.vat);if(byId('v44LineNet'))byId('v44LineNet').textContent=money(t.net);if(byId('v44LineVat'))byId('v44LineVat').textContent=money(t.vat);if(byId('v44LineGross'))byId('v44LineGross').textContent=money(g);byId('invGross').value=g;byId('invVatRate').value='custom';byId('invCustomVat').value=A.round2(t.vat)}

const legacyOpenInvoice=window.openInvoice;
window.openInvoice=function(index=null){legacyOpenInvoice(index);ensureV44Data();const r=index===null?null:data.invoices[index];lineDraft=r?A.parseLines(r):[{id:A.makeId('LIN'),description:'',quantity:1,unitNet:0,vatRate:21,vatTreatment:'NL_HIGH'}];renderLineEditor();byId('invSupplyDate').value=A.iso(r?.['Supply date']||r?.Date);const alreadyIssued=r&&visibleStatus(r)!=='draft';byId('invNo').readOnly=!!alreadyIssued;if(!r){byId('invNo').value='';byId('invStatus').value='Draft'}else byId('invStatus').value=statusLabel[visibleStatus(r)]||r.Status||'Open';byId('invoiceModalTitle').textContent=r?'Edit invoice':'New invoice'};
function invoiceFromEditor(){
  readLineEditor();const t=draftTotals(),existing=editingInvoiceIndex===null?null:data.invoices[editingInvoiceIndex],choice=byId('invStatus').value,isDraft=choice==='Draft';let no=byId('invNo').value.trim();
  if(!isDraft&&!no)no=nextInvoiceNo(byId('invDate').value);if(existing&&visibleStatus(existing)!=='draft')no=existing['Invoice #'];
  const row={...(existing||{}),'Record ID':existing?.['Record ID']||existing?._rid||A.makeId('INV'),'Invoice #':no,'Invoice date':excelSerial(byId('invDate').value),Date:excelSerial(byId('invDate').value),'Supply date':excelSerial(byId('invSupplyDate').value||byId('invDate').value),Customer:byId('invCustomer').value.trim(),Address:byId('invAddress').value.trim(),'Work description':lineDraft.map(l=>l.description).filter(Boolean).join(' | '),Contact:byId('invContact').value.trim(),'Line items JSON':JSON.stringify(lineDraft),'Invoice subtotal':A.round2(t.net),VAT:A.round2(t.vat),'Gross incl. VAT':A.round2(t.net+t.vat),'Net revenue':A.round2(t.net),Parking:0,'Other costs':0,'VAT treatment':'MIXED_OR_LINES','VAT rate':'Lines',Status:choice,'Lifecycle status':choice.toLowerCase().replace(/ /g,'_').replace('open','issued'),'Due date':excelSerial(byId('invDue').value),'Paid date':excelSerial(byId('invPaid').value),Notes:byId('invNotes').value.trim()};
  if(!isDraft&&!row['Issued at'])row['Issued at']=new Date().toISOString();return row;
}
function validateInvoice(row){if(!byId('invDate').value||!row.Customer||!lineDraft.length||lineDraft.some(l=>!A.text(l.description)||A.num(l.quantity)<=0||A.num(l.unitNet)<0)){alert('Complete the invoice date, customer and every line item.');return false}if(row.Status!=='Draft'&&!row.Address){alert('Add the customer address before issuing the invoice.');return false}if(row['Gross incl. VAT']<=0){alert('Invoice total must be greater than €0.');return false}if(row['Invoice #']&&data.invoices.some((r,i)=>i!==editingInvoiceIndex&&r['Invoice #']===row['Invoice #'])){alert(`Invoice number ${row['Invoice #']} already exists.`);return false}return confirmPeriodDate(row.Date,'invoice')}
byId('saveInvoiceBtn').onclick=()=>{if(!ensurePeriodEditable('save an invoice'))return;const row=invoiceFromEditor();if(!validateInvoice(row))return;if(editingInvoiceIndex===null)data.invoices.push(row);else data.invoices[editingInvoiceIndex]=row;if(row.Status==='Paid'&&!A.paymentsFor(row,data.payments).length)data.payments.push({id:A.makeId('PAY'),invoiceId:A.invoiceId(row),date:byId('invPaid').value||new Date().toISOString().slice(0,10),amount:row['Gross incl. VAT'],method:'Bank',reference:'Marked paid from invoice'});persist();closeModal('invoiceModal')};
byId('previewInvoiceBtn').onclick=()=>showInvoicePreviewV44(invoiceFromEditor());
byId('deleteInvoiceBtn').onclick=()=>{if(!ensurePeriodEditable('cancel an invoice')||editingInvoiceIndex===null)return;const r=data.invoices[editingInvoiceIndex];if(visibleStatus(r)==='draft'){if(confirm('Delete this unissued draft?')){data.invoices.splice(editingInvoiceIndex,1);persist();closeModal('invoiceModal')}return}if(confirm(`Cancel invoice ${r['Invoice #']}?\n\nIts permanent number and audit trail will be retained.`)){r.Status='Cancelled';r['Lifecycle status']='cancelled';r['Cancelled at']=new Date().toISOString();persist();closeModal('invoiceModal')}};
function showInvoicePreviewV44(r){const t=A.invoiceTotals(r),due=A.iso(r['Due date']),logo=invoiceLogoSrc();window.currentPreviewInvoice=r;byId('invoicePreview').innerHTML=`<div class="ros-invoice-preview"><section class="ros-invoice-page"><div class="ros-invoice-content"><div class="ros-doc-header"><div class="ros-doc-brand"><div class="ros-doc-brandline">${logo?`<img src="${html(logo)}" alt="Renoweet">`:''}<h2>Renoweet</h2></div><p>Renovatie • Timmerwerk • Technische oplossingen<br>Hiridostraat 2c65, 1101 CW Amsterdam<br>KVK 97746312 • BTW NL005285311B07<br>06 43865003 • renoweet@hotmail.com</p></div><div class="ros-doc-title"><h1>FACTUUR</h1><div><strong>Factuurnr.</strong> ${html(r['Invoice #']||'Draft')}<br><strong>Datum</strong> ${html(A.iso(r.Date))}<br><strong>Vervaldatum</strong> ${html(due)}</div></div></div><div class="ros-doc-rule"></div><div class="ros-doc-party"><div><div class="ros-doc-kicker">AAN</div><strong>${html(r.Customer)}</strong><br>${html(r.Address)}</div></div><div class="ros-doc-section-title">Factuuroverzicht</div><table class="ros-doc-table"><colgroup><col><col><col><col></colgroup><thead><tr><th class="d">Omschrijving</th><th class="q">Aantal</th><th class="r">Tarief</th><th class="a">Bedrag</th></tr></thead><tbody>${t.lines.map(l=>{const x=A.lineTotals(l);return `<tr><td class="d">${html(l.description)}<br><small>${html(l.vatRate)}% btw</small></td><td class="q">${l.quantity}</td><td class="r">${money(l.unitNet)}</td><td class="a">${money(x.net)}</td></tr>`}).join('')}</tbody></table><div class="ros-doc-summary"><div class="ros-doc-summary-row"><span class="label">Subtotaal excl. btw</span><strong>${money(t.net)}</strong></div><div class="ros-doc-summary-row"><span class="label">BTW</span><strong>${money(t.vat)}</strong></div><div class="ros-doc-summary-row grand"><span class="label">Totaal</span><strong>${money(t.gross)}</strong></div></div><div class="ros-invoice-terms"><p><b>Betaling</b></p><p>Betaling op NL45INGB0111929547 onder vermelding van factuurnummer ${html(r['Invoice #']||'')}.</p></div></div><div class="ros-invoice-footer"><span>Renoweet • Slim en Duurzaam. Voor elke klus.</span><span>${html(r['Invoice #']||'Draft')}</span></div></section></div>`;openModal('previewModal')}

function injectExpenseFields(){const modal=byId('expenseModal')?.querySelector('.form-grid');if(!modal||byId('expVatDeductible'))return;const box=document.createElement('div');box.className='v44-section wide';box.style.gridColumn='1/-1';box.innerHTML=`<div class="v44-section-head"><div><div class="v44-eyebrow">Accounting</div><h3>Deduction and payment</h3></div></div><div class="v44-modal-grid"><div class="field"><label>VAT deductible %</label><input id="expVatDeductible" type="number" min="0" max="100" step="1" value="100"></div><div class="field"><label>Income-tax deductible %</label><input id="expIncomeDeductible" type="number" min="0" max="100" step="1" value="100"></div><div class="field"><label>VAT treatment</label><select id="expVatTreatment"><option>NL_HIGH</option><option>NL_LOW</option><option>NL_ZERO</option><option>REVERSE_CHARGE_NL</option><option>EU_B2B</option><option>EXEMPT</option><option>CUSTOM</option></select></div><div class="field"><label>Payment status</label><select id="expPaymentStatus"><option>Paid</option><option>Unpaid</option></select></div><div class="field"><label>Payment date</label><input id="expPaymentDate" type="date"></div><div class="field"><label>Payment method</label><select id="expPaymentMethod"><option>Bank</option><option>Card</option><option>Cash</option><option>Other</option></select></div></div>`;modal.appendChild(box)}
const legacyOpenExpense=window.openExpense;
window.openExpense=function(type='General',index=null){legacyOpenExpense(type,index);const arr=type==='Fuel'?data.fuel:type==='Automobile'?data.auto:data.expenses,r=index===null?{}:arr[index];byId('expVatDeductible').value=r['VAT deductible %']??100;byId('expIncomeDeductible').value=r['Income tax deductible %']??r['Business use %']??100;byId('expVatTreatment').value=r['VAT treatment']||((inferVatRate(r,false)==='9')?'NL_LOW':(inferVatRate(r,false)==='0'?'NL_ZERO':'NL_HIGH'));byId('expPaymentStatus').value=r['Payment status']||'Paid';byId('expPaymentDate').value=A.iso(r['Payment date']||r.Date);byId('expPaymentMethod').value=r['Payment method']||'Bank'};
byId('saveExpenseBtn').onclick=async()=>{
  const originalType=byId('expType').value,gross=A.num(byId('expGross').value),invoiceVat=byId('expVatRate').value==='custom'?Math.max(0,A.num(byId('expCustomVat').value)):calcVat(gross,byId('expVatRate').value),existingProof=byId('expReceipt').value.trim();if(gross<=0){alert('Gross amount must be greater than €0.');return}if(invoiceVat<0||invoiceVat>gross){alert('VAT must be between €0 and the gross amount.');return}if(!existingProof&&!pendingProofFile){alert('Attach a PDF or image proof before saving this expense.');return}
  let proofName=existingProof;if(pendingProofFile){try{proofName=await storeProofFile(pendingProofFile,originalType)}catch(e){alert('Could not store proof: '+e.message);return}}if(!ensurePeriodEditable('save an expense'))return;
  const sourceArr=editingExpense.type==='Fuel'?data.fuel:editingExpense.type==='Automobile'?data.auto:data.expenses,prev=editingExpense.index===null?null:sourceArr[editingExpense.index],vatPct=Math.max(0,Math.min(100,A.num(byId('expVatDeductible').value))),incomePct=Math.max(0,Math.min(100,A.num(byId('expIncomeDeductible').value))),dedVat=A.round2(invoiceVat*vatPct/100),net=A.round2(gross-invoiceVat),costBase=A.round2(net+invoiceVat-dedVat),proofMeta=window.__renoweetProofUploadMeta||null;
  const category=originalType==='Fuel'?'Fuel':originalType==='Automobile'?'Vehicle':byId('expCategory').value.trim();const row={...(prev||{}),'Record ID':prev?.['Record ID']||prev?._rid||A.makeId('EXP'),'Document date':excelSerial(byId('expDate').value),Date:excelSerial(byId('expDate').value),Supplier:byId('expSupplier').value.trim(),Category:category,Description:byId('expDescription').value.trim(),Gross:gross,'Invoice VAT':A.round2(invoiceVat),VAT:A.round2(invoiceVat),'VAT rate':byId('expVatRate').value==='custom'?'Other':byId('expVatRate').value,Net:net,'VAT treatment':byId('expVatTreatment').value,'VAT deductible %':vatPct,'Deductible VAT':dedVat,'Income tax deductible %':incomePct,'Deductible cost':A.round2(costBase*incomePct/100),'Payment status':byId('expPaymentStatus').value,'Payment date':excelSerial(byId('expPaymentDate').value),'Payment method':byId('expPaymentMethod').value,'Receipt/File':proofName,'Proof Check':proofExtracted?'Review':(prev?.['Proof Check']||'Not checked'),'Proof Drive ID':proofMeta?.id||prev?.['Proof Drive ID']||'','Proof MIME':proofMeta?.mimeType||prev?.['Proof MIME']||'',Review:byId('expReview').value,Notes:byId('expNotes').value.trim()};
  if(!confirmPeriodDate(row.Date,'expense'))return;const dup=expenseDuplicate(row,'General',editingExpense.type==='General'?editingExpense.index:null);if(dup&&!confirm('A similar expense already exists. Save anyway?'))return;
  if(editingExpense.index===null)data.expenses.push(row);else if(editingExpense.type==='General')data.expenses[editingExpense.index]=row;else{sourceArr.splice(editingExpense.index,1);data.expenses.push(row)}pendingProofFile=null;proofExtracted=null;window.__renoweetProofUploadMeta=null;persist();closeModal('expenseModal');
};

function ensureMoneyModal(){if(byId('v44MoneyModal'))return;const el=document.createElement('div');el.className='modal';el.id='v44MoneyModal';el.innerHTML=`<div class="modal-card" style="max-width:620px"><div class="modal-head"><h3 id="v44MoneyTitle">Record payment</h3><button class="secondary" type="button" data-v44-close>Close</button></div><div class="v44-modal-grid"><div class="field wide"><label>Invoice</label><select id="v44MoneyInvoice"></select></div><div class="field"><label>Date</label><input id="v44MoneyDate" type="date"></div><div class="field"><label>Amount incl. VAT (€)</label><input id="v44MoneyAmount" type="number" min="0.01" step="0.01"></div><div class="field"><label>Method</label><select id="v44MoneyMethod"><option>Bank</option><option>Card</option><option>Cash</option><option>Other</option></select></div><div class="field"><label>Reference</label><input id="v44MoneyReference"></div><div class="field wide" id="v44CreditReasonField" hidden><label>Credit reason</label><input id="v44CreditReason"></div></div><div class="modal-foot"><button class="green" id="v44MoneySave">Save</button></div></div>`;document.body.appendChild(el);el.querySelector('[data-v44-close]').onclick=()=>el.classList.remove('open');el.onclick=e=>{if(e.target===el)el.classList.remove('open')}}
function openMoney(kind,id){ensureMoneyModal();const options=data.invoices.filter(r=>r['Invoice #']).map(r=>`<option value="${html(A.invoiceId(r))}" ${A.invoiceId(r)===id?'selected':''}>${html(r['Invoice #'])} — ${html(r.Customer)}</option>`).join('');byId('v44MoneyInvoice').innerHTML=options;byId('v44MoneyDate').value=new Date().toISOString().slice(0,10);const inv=rowRef(id),st=inv?stateFor(inv):null;byId('v44MoneyAmount').value=st?.outstanding||'';byId('v44MoneyTitle').textContent=kind==='credit'?'Create credit note':'Record customer payment';byId('v44CreditReasonField').hidden=kind!=='credit';byId('v44MoneySave').onclick=()=>saveMoney(kind);byId('v44MoneyModal').classList.add('open')}
function saveMoney(kind){if(!ensurePeriodEditable(kind==='credit'?'create a credit note':'record a payment'))return;const id=byId('v44MoneyInvoice').value,inv=rowRef(id),amount=A.num(byId('v44MoneyAmount').value),date=byId('v44MoneyDate').value;if(!inv||!date||amount<=0){alert('Choose an invoice, date and positive amount.');return}if(kind==='payment')data.payments.push({id:A.makeId('PAY'),invoiceId:id,'Invoice #':inv['Invoice #'],date,amount:A.round2(amount),method:byId('v44MoneyMethod').value,reference:byId('v44MoneyReference').value.trim()});else{const t=A.invoiceTotals(inv),ratio=Math.min(1,amount/t.gross);data.creditNotes.push({id:A.makeId('CRN'),invoiceId:id,'Invoice #':inv['Invoice #'],date,gross:A.round2(amount),net:A.round2(t.net*ratio),vat:A.round2(amount-t.net*ratio),reason:byId('v44CreditReason').value.trim()});}byId('v44MoneyModal').classList.remove('open');persist()}
window.recordV44Payment=id=>openMoney('payment',id);window.createV44Credit=id=>openMoney('credit',id);

function kpi(label,value,sub){return `<div class="v44-kpi"><div class="eyebrow">${html(label)}</div><strong>${value}</strong><small>${html(sub||'')}</small></div>`}
function renderDashboardV44(){const p=activePeriod(),pl=A.profitAndLoss(data,p),cash=A.cashReport(data,p),vat=A.vatReport(data,p),receivable=A.receivables(data),health=A.controls(data),open=data.invoices.filter(r=>['issued','partially_paid','overdue'].includes(visibleStatus(r)));byId('dashboard').innerHTML=`<div class="v44-shell"><div class="panel-head"><div><div class="v44-eyebrow">Accounting overview • ${p.label}</div><h2>Bookkeeping</h2><div class="chart-sub">Issued revenue, cash and VAT are calculated independently.</div></div><span class="v44-state">Accounting core 4.4</span></div><div class="v44-kpis">${kpi('Revenue ex VAT',money(pl.revenue),'Issued invoices in this quarter')}${kpi('Cash received',money(cash.cashIn),'Customer payments received')}${kpi('Receivables',money(receivable),`${open.length} open / partial / overdue`)}${kpi('Business costs',money(pl.directCosts+pl.operatingExpenses),'Deductible accounting cost')}${kpi('Accounting result',money(pl.operatingProfit),'Revenue minus deductible costs')}${kpi('Cash movement',money(cash.movement),'Cash in minus cash out')}${kpi(vat.position>=0?'VAT payable':'VAT receivable',money(Math.abs(vat.position)),'Issued sales VAT minus deductible input VAT')}${kpi('Accounting health',`${health.score}/100`,health.issues.length?`${health.issues.length} item(s) to review`:'Books ready for review')}</div><div class="v44-summary"><div class="card panel"><div class="panel-head"><h2>Outstanding invoices</h2><button class="secondary" onclick="document.querySelector('[data-view=invoices]').click()">Open Sales</button></div>${open.length?`<div class="table-wrap"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Status</th><th class="money">Outstanding</th></tr></thead><tbody>${open.slice(0,8).map(r=>{const s=stateFor(r);return `<tr><td>${html(r['Invoice #'])}</td><td>${html(r.Customer)}</td><td><span class="v44-state ${s.status}">${html(statusLabel[s.status])}</span></td><td class="money">${money(s.outstanding)}</td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">No outstanding invoices.</div>'}</div><div class="card panel"><div class="v44-health"><div class="v44-score">${health.score}<small>/ 100</small></div><div><h2>Accounting health</h2><p class="v44-note">${health.issues.length?'Review the highest-impact controls before filing.':'No accounting control warnings found.'}</p></div></div><div class="v44-list" style="margin-top:14px">${health.issues.slice(0,4).map(x=>`<div class="v44-alert ${x.level}">${html(x.message)}</div>`).join('')}</div></div></div></div>`}
function renderSales(){const rows=data.invoices;byId('invoices').innerHTML=`<div class="card panel"><div class="panel-head"><div><h2>Sales ledger</h2><div class="chart-sub">Draft → issued → paid. Permanent invoice numbers are locked after issue.</div></div><div class="report-actions"><button class="secondary" onclick="printInvoices()">Print register</button><button class="green" onclick="openInvoice()">+ New invoice</button></div></div>${rows.length?`<div class="table-wrap"><table><thead><tr><th>Invoice</th><th>Date</th><th>Customer</th><th>Status</th><th class="money">Net</th><th class="money">VAT</th><th class="money">Outstanding</th><th>Actions</th></tr></thead><tbody>${rows.map((r,i)=>{const t=A.invoiceTotals(r),s=stateFor(r);return `<tr><td><b>${html(r['Invoice #']||'Draft')}</b><br><small>${html(A.invoiceId(r))}</small></td><td>${html(A.iso(r.Date))}</td><td>${html(r.Customer)}</td><td><span class="v44-state ${s.status}">${html(statusLabel[s.status])}</span></td><td class="money">${money(t.net)}</td><td class="money">${money(t.vat)}</td><td class="money">${money(s.outstanding)}</td><td><div class="v44-ledger-actions"><button class="secondary" onclick="openInvoice(${i})">Edit</button>${!['draft','cancelled','credited'].includes(s.status)?`<button class="secondary" onclick="recordV44Payment('${html(A.invoiceId(r))}')">Payment</button><button class="secondary" onclick="createV44Credit('${html(A.invoiceId(r))}')">Credit</button>`:''}</div></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">No invoices yet.</div>'}<div class="v44-section"><div class="v44-section-head"><div><div class="v44-eyebrow">Cash ledger</div><h3>Customer payments</h3></div></div>${data.payments.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Invoice</th><th>Method</th><th>Reference</th><th class="money">Amount</th></tr></thead><tbody>${data.payments.map(p=>`<tr><td>${html(A.iso(p.date||p.Date))}</td><td>${html(p['Invoice #']||rowRef(p.invoiceId)?.['Invoice #'])}</td><td>${html(p.method||p.Method)}</td><td>${html(p.reference||p.Reference)}</td><td class="money">${money(p.amount||p.Amount)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No separate payment records yet. Legacy Paid invoices still count as received cash.</div>'}</div></div>`}
function renderExpenses(){const rows=expenseSources(),tot=rows.reduce((a,x)=>{const f=A.expenseFacts(x.r);a.gross+=f.gross;a.vat+=f.deductibleVat;a.cost+=f.deductibleCost;return a},{gross:0,vat:0,cost:0});byId('expenses').innerHTML=`<div class="card panel"><div class="panel-head"><div><h2>Expense ledger</h2><div class="chart-sub">General, fuel and vehicle costs use one accounting calculation.</div></div><div class="report-actions"><button class="secondary" onclick="printExpenses()">Print report</button><button class="secondary" onclick="connectProofFolder()">Proofs: Google Drive</button><button class="green" onclick="openExpense('General')">+ Add expense</button></div></div><div class="v44-kpis">${kpi('Gross spending',money(tot.gross),`${rows.length} expense(s)`)}${kpi('Deductible input VAT',money(tot.vat),'VAT return amount')}${kpi('Deductible cost',money(tot.cost),'P&L / tax helper amount')}</div>${rows.length?`<div class="table-wrap" style="margin-top:16px"><table><thead><tr><th>Date</th><th>Supplier</th><th>Category</th><th>Description</th><th class="money">Gross</th><th class="money">Invoice VAT</th><th class="money">Deductible VAT</th><th class="money">Deductible cost</th><th>Proof</th><th></th></tr></thead><tbody>${rows.map(x=>{const f=A.expenseFacts(x.r);return `<tr><td>${html(A.iso(x.r['Document date']||x.r.Date))}</td><td>${html(x.r.Supplier)}</td><td>${html(x.r.Category||x.type)}</td><td>${html(x.r.Description)}</td><td class="money">${money(f.gross)}</td><td class="money">${money(f.invoiceVat)}</td><td class="money">${money(f.deductibleVat)}</td><td class="money">${money(f.deductibleCost)}</td><td>${x.r['Receipt/File']?'Verified / linked':'Missing'}</td><td><button class="secondary" onclick="openExpense('${x.type}',${x.index})">Edit</button></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">No expenses yet.</div>'}</div>`}
function renderVat(){const p=activePeriod(),v=A.vatReport(data,p);byId('btwReport').innerHTML=`${btwControlHtml()}<div class="card panel"><div class="panel-head"><div><h2>VAT / BTW • ${p.label}</h2><div class="chart-sub">One result shared with Dashboard and Reports.</div></div><button class="secondary" onclick="printBTWReport()">Print report</button></div><div class="v44-kpis">${kpi('Sales ex VAT',money(v.salesNet),`${v.issued.length} issued invoice(s)`)}${kpi('Output VAT',money(v.outputVat),'Issued sales and credit notes')}${kpi('Deductible input VAT',money(v.inputVat),'Eligible purchase VAT')}${kpi(v.position>=0?'BTW payable':'BTW receivable',money(Math.abs(v.position)),'Canonical VAT position')}</div><div class="v44-section"><h3>Calculation</h3><table class="v44-statement"><tr><td>Output VAT on issued sales</td><td>${money(v.outputVat)}</td></tr><tr><td>Less: deductible input VAT</td><td>− ${money(v.inputVat)}</td></tr><tr class="total"><td>${v.position>=0?'BTW payable':'BTW receivable'}</td><td>${money(Math.abs(v.position))}</td></tr></table><p class="v44-note">Payment status does not change output VAT. Draft and cancelled invoices are excluded. Expense VAT uses the explicit deductible amount.</p></div></div>`}
function renderReports(){const p=yearPeriod(),pl=A.profitAndLoss(data,p),cash=A.cashReport(data,p),vat=A.vatReport(data,p),rec=A.receivables(data);byId('incomeTax').innerHTML=`<div class="v44-shell"><div class="panel-head"><div><div class="v44-eyebrow">Reports • ${p.label}</div><h2>Accounting and cash</h2></div></div><div class="v44-report-grid"><div class="card panel"><h2>Profit & loss</h2><table class="v44-statement"><tr><td>Revenue ex VAT</td><td>${money(pl.revenue)}</td></tr><tr><td>Direct costs</td><td>− ${money(pl.directCosts)}</td></tr><tr><td>Gross profit</td><td>${money(pl.grossProfit)}</td></tr><tr><td>Operating expenses</td><td>− ${money(pl.operatingExpenses)}</td></tr><tr class="total"><td>Operating profit</td><td>${money(pl.operatingProfit)}</td></tr></table></div><div class="card panel"><h2>Cash report</h2><table class="v44-statement"><tr><td>Customer payments received</td><td>${money(cash.cashIn)}</td></tr><tr><td>Supplier payments made</td><td>− ${money(cash.cashOut)}</td></tr><tr class="total"><td>Operating cash movement</td><td>${money(cash.movement)}</td></tr></table><p class="v44-note">Cash is separate from recognised revenue and costs.</p></div><div class="card panel"><h2>Balance helper</h2><table class="v44-statement"><tr><td>Accounts receivable</td><td>${money(rec)}</td></tr><tr><td>${vat.position>=0?'VAT payable':'VAT receivable'}</td><td>${money(Math.abs(vat.position))}</td></tr></table><p class="v44-note">Bank, cash, fixed assets and loans remain manual year-end inputs in v4.4.</p></div><div class="card panel"><h2>Estimated income-tax helper</h2><table class="v44-statement"><tr><td>Accounting profit</td><td>${money(pl.operatingProfit)}</td></tr><tr><td>Recorded tax adjustments</td><td>${money(0)}</td></tr><tr class="total"><td>Estimated taxable profit</td><td>${money(pl.estimatedTaxableProfit)}</td></tr></table><p class="v44-note">Estimate only. Review special deductions and year-end adjustments with your accountant.</p></div></div></div>`}
function renderControl(){const c=A.controls(data),deleted=data.deleted||[];byId('deleted').innerHTML=`<div class="v44-shell"><div class="card panel"><div class="v44-health"><div class="v44-score">${c.score}<small>/ 100</small></div><div><h2>Bookkeeping control</h2><p class="v44-note">Sales, expenses, VAT and payment checks in one pre-filing review.</p></div></div><div class="v44-list" style="margin-top:16px">${c.issues.length?c.issues.map(x=>`<div class="v44-alert ${x.level}"><b>${html(x.kind.toUpperCase())}</b> · ${html(x.message)}</div>`).join(''):'<div class="v44-alert info">No control issues found.</div>'}</div></div><div class="card panel"><h2>Cancelled and deleted records</h2>${deleted.length?makeTable(deleted,['Deleted at','Type','Record ID','Customer / Supplier','Description','Gross','VAT','Net','Status'],'readonly'):'<div class="empty">No deleted records.</div>'}</div></div>`}

const legacyRender=window.render;
window.render=function(...args){ensureV44Data();legacyRender.apply(this,args);renderDashboardV44();renderSales();renderExpenses();renderVat();renderReports();renderControl()};
function configureNavigation(){const labels={dashboard:'Overview',invoices:'Sales',expenses:'Expenses',btwReport:'VAT',incomeTax:'Reports',deleted:'Control'};document.querySelectorAll('nav.tabs .tab').forEach(b=>{if(labels[b.dataset.view])b.textContent=labels[b.dataset.view];else b.hidden=true});document.body.classList.add('v44-ready')}
function boot(){injectInvoiceEditor();injectExpenseFields();ensureMoneyModal();configureNavigation();ensureV44Data();render();const status=byId('status');if(status&&!/connected/i.test(status.textContent))status.textContent='Focus Hub v4.4 ready • connect Google Drive to load the accounting database'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,750));else setTimeout(boot,750);
})();
