(function(root){
'use strict';
const VERSION='4.4.1';
const CHECKLIST=['Scope confirmed with customer','Measurements checked','Materials ordered','Access / parking / keys arranged','Work area protected','Before photos taken','Work completed','Quality check completed','Customer walkthrough','Invoice sent','Review request sent','Referral request sent'];
const DEFAULT_EXCLUSIONS='Niet inbegrepen tenzij expliciet vermeld:\n- Vergunningen, constructieberekeningen en werkzaamheden van derden.\n- Verborgen gebreken, asbest of niet-zichtbare leidingen/constructies.\n- Herstelwerk buiten de omschreven scope.';
const DEFAULT_PAYMENT='Na akkoord op deze offerte is een aanbetaling verschuldigd ter voorbereiding en uitvoering van de werkzaamheden volgens planning. Het resterende bedrag wordt betaald volgens de afgesproken termijn(en), met de eindbetaling bij oplevering. Betalingstermijnen en vervaldata zijn conform de offerte en gemaakte afspraken.';
const DEFAULT_ASSUMPTIONS='Uitvoering op basis van zichtbare situatie en beschikbare informatie tijdens inspectie. Definitieve maten, materiaalkeuzes en bereikbaarheid worden vóór start bevestigd.';

function text(v){return String(v??'').trim()}
function norm(v){return text(v).toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'')}
function round2(v){return Math.round((Number(v)||0)*100)/100}
function number(v){if(typeof v==='number'&&Number.isFinite(v))return v;const s=text(v).replace(/\s/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0}
function hash(value){let a=2166136261,b=3339675911;for(const ch of String(value)){const c=ch.charCodeAt(0);a=Math.imul(a^c,16777619);b=Math.imul(b^c,2246822519)}return ((a>>>0).toString(16).padStart(8,'0')+(b>>>0).toString(16).padStart(8,'0')).toUpperCase()}
function invoiceNumber(v){return text(v).toUpperCase().replace(/\s+/g,'').replace(/[–—]/g,'-')}
function isoDate(year,month,day){year=Number(year);month=Number(month);day=Number(day);const d=new Date(Date.UTC(year,month-1,day));if(d.getUTCFullYear()!==year||d.getUTCMonth()!==month-1||d.getUTCDate()!==day)return '';return `${String(year).padStart(4,'0')}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`}
function addDays(iso,days){const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+Number(days||0));return d.toISOString().slice(0,10)}
function quarterFor(iso){const month=Number(String(iso).slice(5,7));return Math.ceil(month/3)}
function parseInvoiceDate(value){const inv=invoiceNumber(value),m=inv.match(/^(20\d{2})-(\d{2})(\d{2})/);return m?isoDate(m[1],m[3],m[2]):''}
function parseLegacyDate(value,year){
 if(value instanceof Date&&!Number.isNaN(value.valueOf()))return isoDate(value.getUTCFullYear(),value.getUTCMonth()+1,value.getUTCDate());
 if(typeof value==='number'&&Number.isFinite(value)){const d=new Date(Date.UTC(1899,11,30)+Math.round(value)*86400000);return isoDate(d.getUTCFullYear(),d.getUTCMonth()+1,d.getUTCDate())}
 const s=text(value);if(!s)return '';
 let m=s.match(/^(20\d{2})[-/.](\d{1,2})[-/.](\d{1,2})/);if(m)return isoDate(m[1],m[2],m[3]);
 m=s.match(/^(\d{1,2})[/.](\d{1,2})(?:[/.](20\d{2}))?/);if(m)return isoDate(m[3]||year,m[2],m[1]);
 const digits=s.replace(/\D/g,'');if(digits.length>=8&&/^\d{8}/.test(digits)){const d=digits.slice(0,8),tailYear=Number(d.slice(4,8));if(tailYear>=2000)return isoDate(tailYear,d.slice(2,4),d.slice(0,2));const leadYear=Number(d.slice(0,4));if(leadYear>=2000)return isoDate(leadYear,d.slice(4,6),d.slice(6,8))}
 if(digits.length>=4)return isoDate(year,digits.slice(2,4),digits.slice(0,2));return '';
}
function inPeriod(iso,year,quarter){return String(iso).startsWith(`${year}-`)&&quarterFor(iso)===Number(quarter)}
function mapHeader(row){const out={};(row||[]).forEach((v,i)=>{const k=norm(v);if(k&&!Object.prototype.hasOwnProperty.call(out,k))out[k]=i});return out}
function firstIndex(map,tests){for(const [key,index] of Object.entries(map))if(tests.some(test=>test(key)))return index;return -1}
function recordId(prefix,key){return `${prefix}_legacy_${hash(key).toLowerCase()}`}
function sourceKey(year,quarter,type,key){return `legacy-xlsx-${year}q${quarter}-${type}-${key}`}
function contactFields(value){const v=text(value);if(v.includes('@'))return {email:v,phone:''};return {email:'',phone:v}}
function customerId(name,address){return `cus_legacy_${hash(`${norm(name)}|${norm(address)}`).toLowerCase()}`}
function standardChecklist(key){return CHECKLIST.map((item,index)=>({order:index+1,text:item,done:index===0,id:`chk_legacy_${hash(`${key}|${index}`).toLowerCase()}`}))}
function categoryFor(supplier,description){const s=norm(`${supplier} ${description}`);if(/easypark|qpark|parking|garage|auto|oil|filter/.test(s))return 'Vehicle';if(/hornbach|gamma|bouwmaat|pakhuis|ikea/.test(s))return 'Materials';if(/werkspot|advert|marketing/.test(s))return 'Marketing';if(/lidl|jumbo|ah|food|mado|taco/.test(s))return 'Meals';if(/bol|software|online|telefoon|phone/.test(s))return 'Software';return 'General'}
function expenseFingerprint(row,type){return [type,row.Date,norm(row.Supplier),round2(row.Gross).toFixed(2),round2(row['Invoice VAT']??row.VAT).toFixed(2),norm(row.Description)].join('|')}

function makeSale(row,headers,selection,source,rowNumber){
 const idx={invoice:firstIndex(headers,[k=>k.startsWith('factuur')||k==='invoice']),gross:firstIndex(headers,[k=>k==='inbrutu'||k.includes('gross')]),parking:firstIndex(headers,[k=>k==='parking']),other:firstIndex(headers,[k=>k==='othercosts'||k==='overigekosten']),vat:firstIndex(headers,[k=>k==='btw'||k==='vat']),customer:firstIndex(headers,[k=>k==='issuedto'||k==='customer']),address:firstIndex(headers,[k=>k==='adres'||k==='address']),description:firstIndex(headers,[k=>k==='workdescription'||k==='description']),contacts:firstIndex(headers,[k=>k==='contacts'||k==='contact'])};
 const inv=invoiceNumber(row[idx.invoice]);if(!/^(19|20)\d{2}-/.test(inv))return null;const date=parseInvoiceDate(inv),gross=round2(number(row[idx.gross]));if(!gross)return {rejected:{sheet:source.sheet,row:rowNumber,record:inv,reason:'Invoice has no gross amount'}};if(!date)return {rejected:{sheet:source.sheet,row:rowNumber,record:inv,reason:'Invoice date could not be read from its number'}};if(!inPeriod(date,selection.year,selection.quarter))return {outside:{sheet:source.sheet,row:rowNumber,record:inv,date,reason:'Outside selected quarter'}};
 const parking=round2(number(row[idx.parking])),other=round2(number(row[idx.other])),taxableGross=round2(gross-parking-other),sourceVat=round2(number(row[idx.vat])),vat=sourceVat||round2(taxableGross*21/121),net=round2(taxableGross-vat),customer=text(row[idx.customer]),address=text(row[idx.address]),description=text(row[idx.description])||'Legacy invoiced work - details to complete',contacts=contactFields(row[idx.contacts]),key=sourceKey(selection.year,selection.quarter,'invoice',norm(inv)),projectId=`PLEGACY-${selection.year}Q${selection.quarter}-${hash(inv).slice(0,12)}`,rid=recordId('inv',key),due=addDays(date,3),review=!customer||!text(row[idx.description]);
 const project={id:projectId,created:date,updated:`${date}T12:00:00.000Z`,stage:'Completed',customer:{id:customerId(customer,address),name:customer,phone:contacts.phone,email:contacts.email,address},title:text(row[idx.description])||`Legacy project - invoice ${inv}`,description,scope:description,notes:`Imported from ${source.name}, ${selection.year} Q${selection.quarter}. Payment status was not proven by the workbook and remains for review.${review?' Customer or work details are incomplete and should be checked.':''}`,estimate:[{id:`est_legacy_${hash(key).slice(0,12).toLowerCase()}`,desc:description,qty:1,unit:'LS',rate:net}],materials:[],documents:[],payments:[],purchaseOrders:[],activity:[{id:`act_legacy_${hash(key).slice(0,12).toLowerCase()}`,timestamp:`${date}T12:00:00.000Z`,type:'Legacy import',text:`Invoice ${inv} imported from ${source.name}.`}],followUps:[],acceptance:{status:'Pending',date:'',notes:'Historical acceptance was not present in the workbook.'},schedule:{start:'',end:'',time:'',endTime:'',notes:'',shareClient:false,inviteEmail:'',inviteStatus:'',calendarSharedWith:'',calendarShareSignature:'',calendarEventId:'',calendarHtmlLink:'',calendarSyncedAt:''},quote:{number:'',date,validDays:14,vat:21,status:'Draft',parking:round2(parking+other),travel:0,exclusions:DEFAULT_EXCLUSIONS,paymentTerms:DEFAULT_PAYMENT,advancePct:50,installments:0,assumptions:DEFAULT_ASSUMPTIONS},invoice:{number:inv,date,dueDays:3,status:'Sent'},checklist:standardChecklist(key),legacySourceKey:key,legacyImport:{version:VERSION,key,year:selection.year,quarter:selection.quarter,sourceFile:source.name,sourceHash:source.sha256||'',sourceSheet:source.sheet,sourceRow:rowNumber,invoiceNumber:inv,otherCosts:other,reviewRequired:review}};
 const invoice={'Invoice #':inv,Date:date,'Invoice date':date,'Supply date':date,Customer:customer,Contact:text(row[idx.contacts]),Address:address,'Work description':description,'Gross incl. VAT':gross,Parking:parking,'Other costs':other,'VAT rate':'21',VAT:vat,'Net revenue':net,Status:'Unknown','Due date':due,'Paid date':'',Notes:`Imported from ${source.name}. Payment status requires review.`,_migrationKey:key,'Project ID':projectId,'Original Invoice #':inv,_rid:rid,'Record ID':rid,'Line items JSON':JSON.stringify([{id:`line_${hash(key).slice(0,10).toLowerCase()}`,description,quantity:1,unitNet:net,vatRate:21,vatTreatment:'NL_HIGH',vatAmount:vat}]),'Invoice subtotal':net,'VAT treatment':'NL_HIGH','Lifecycle status':'issued','Issued at':`${date}T12:00:00.000Z`,'Legacy source file':source.name,'Legacy source hash':source.sha256||'','Legacy source row':rowNumber,'Legacy review':review?'Review':''};
 return {project,invoice};
}

function makeExpense({type,date,gross,vat,supplier,description,source,rowNumber,selection,occurrence}){
 gross=round2(gross);vat=round2(vat);const net=round2(gross-vat),category=type==='fuel'?'Fuel':type==='auto'?'Vehicle':categoryFor(supplier,description),base=[selection.year,selection.quarter,type,date,norm(supplier),gross.toFixed(2),vat.toFixed(2),norm(description)].join('|'),fingerprint=[type,date,norm(supplier),gross.toFixed(2),vat.toFixed(2),norm(description)].join('|'),key=sourceKey(selection.year,selection.quarter,type,`${hash(base).toLowerCase()}-${occurrence}`),rid=recordId(type==='fuel'?'fuel':type==='auto'?'auto':'exp',key),expected=round2(gross*21/121),rate=Math.abs(expected-vat)<=0.03?'21':'Other',review=!supplier||rate==='Other';
 return {'Record ID':rid,_rid:rid,'Document date':date,Date:date,Supplier:supplier,Category:category,Description:description,Gross:gross,'Invoice VAT':vat,VAT:vat,'VAT rate':rate,Net:net,'VAT treatment':rate==='21'?'NL_HIGH':'CUSTOM','VAT deductible %':100,'Deductible VAT':vat,'Income tax deductible %':100,'Deductible cost':net,'Payment status':'Paid','Payment date':date,'Payment method':'','Receipt/File':'','Proof Check':'Missing',Review:review?'Review':'',Notes:`Imported from ${source.name}. VAT deductibility, proof and payment details should be reviewed.`,_migrationKey:key,'Source database':source.name,'Legacy source hash':source.sha256||'','Legacy source sheet':source.sheet,'Legacy source row':rowNumber,'Legacy fingerprint':fingerprint,'Legacy occurrence':occurrence,_legacyFingerprint:fingerprint,_legacyOccurrence:occurrence};
}

function parseExpenses(sheets,selection,source,prepared){
 const occurrences=new Map();
 const push=(type,args)=>{const fingerprint=[type,args.date,norm(args.supplier),round2(args.gross).toFixed(2),round2(args.vat).toFixed(2),norm(args.description)].join('|'),occurrence=(occurrences.get(fingerprint)||0)+1;occurrences.set(fingerprint,occurrence);const record=makeExpense({...args,type,selection,occurrence});prepared.records[type==='fuel'?'fuel':type==='auto'?'auto':'expenses'].push(record)};
 for(const sheet of sheets){const rows=sheet.rows||[];for(let h=0;h<Math.min(rows.length,30);h++){const header=rows[h]||[],keys=header.map(norm),generalStart=keys.indexOf('iddate');if(generalStart>=0&&keys[generalStart+1]==='amount')for(let r=h+1;r<rows.length;r++){const row=rows[r]||[],rawDate=row[generalStart],gross=round2(number(row[generalStart+1]));if(!gross)continue;const supplier=text(row[generalStart+4]),description=text(row[generalStart+6]);if(rawDate==null||text(rawDate)===''){prepared.rejected.push({sheet:sheet.name,row:r+1,record:`${supplier} ${gross}`.trim(),reason:'Expense has no usable date'});continue}const date=parseLegacyDate(rawDate,selection.year);if(!date){prepared.rejected.push({sheet:sheet.name,row:r+1,record:`${supplier} ${gross}`.trim(),reason:'Expense date could not be read'});continue}if(!inPeriod(date,selection.year,selection.quarter)){prepared.outside.push({sheet:sheet.name,row:r+1,record:`${supplier} ${gross}`.trim(),date,reason:'Outside selected quarter'});continue}const cachedVat=round2(number(row[generalStart+2])),customRaw=row[generalStart+3],hasCustom=customRaw!==null&&text(customRaw)!=='',vat=hasCustom?round2(number(customRaw)):(cachedVat||round2(gross*21/121)),joined=norm(`${supplier} ${description}`),type=/auto|oil|filter|garage/.test(joined)?'auto':'expenses';push(type,{date,gross,vat,supplier,description,source:{...source,sheet:sheet.name},rowNumber:r+1})}
   for(let start=0;start<header.length-2;start++){if(keys[start]!=='bill'||keys[start+1]!=='date'||keys[start+2]!=='amount')continue;const label=norm(rows[h-1]?.[start]||''),type=label.includes('fuel')?'fuel':'expenses',categoryLabel=label.includes('online')?'Online service':label.includes('bill')?'Bill':'';for(let r=h+1;r<rows.length;r++){const row=rows[r]||[],gross=round2(number(row[start+2]));if(!gross)continue;const date=parseLegacyDate(row[start+1],selection.year),supplier=text(row[start+4])||categoryLabel;if(!date){prepared.rejected.push({sheet:sheet.name,row:r+1,record:`${supplier} ${gross}`.trim(),reason:'Expense date could not be read'});continue}if(!inPeriod(date,selection.year,selection.quarter)){prepared.outside.push({sheet:sheet.name,row:r+1,record:`${supplier} ${gross}`.trim(),date,reason:'Outside selected quarter'});continue}const vat=round2(number(row[start+3]))||round2(gross*21/121);push(type,{date,gross,vat,supplier,description:categoryLabel,source:{...source,sheet:sheet.name},rowNumber:r+1})}}
  }}
}

function parseSheets(sheets,selection,source={}){
 selection={year:Number(selection.year),quarter:Number(selection.quarter)};if(!Number.isInteger(selection.year)||selection.year<2000||selection.year>2100)throw new Error('Choose a valid year.');if(![1,2,3,4].includes(selection.quarter))throw new Error('Choose quarter Q1-Q4.');
 const prepared={schema:'renoweet.legacy-import',schemaVersion:1,engineVersion:VERSION,generatedAt:new Date().toISOString(),selection,source:{name:text(source.name)||'Legacy workbook.xlsx',size:Number(source.size)||0,sha256:text(source.sha256)},records:{projects:[],invoices:[],expenses:[],fuel:[],auto:[]},rejected:[],outside:[],warnings:[]},seenInvoices=new Set();let salesFound=false;
 for(const sheet of sheets){const rows=sheet.rows||[];for(let h=0;h<Math.min(rows.length,40);h++){const headers=mapHeader(rows[h]),invIndex=firstIndex(headers,[k=>k.startsWith('factuur')||k==='invoice']),grossIndex=firstIndex(headers,[k=>k==='inbrutu'||k.includes('gross')]);if(invIndex<0||grossIndex<0)continue;salesFound=true;for(let r=h+1;r<rows.length;r++){const made=makeSale(rows[r]||[],headers,selection,{...prepared.source,sheet:sheet.name},r+1);if(!made)continue;if(made.rejected){prepared.rejected.push(made.rejected);continue}if(made.outside){prepared.outside.push(made.outside);continue}const inv=made.invoice['Invoice #'];if(seenInvoices.has(inv)){prepared.rejected.push({sheet:sheet.name,row:r+1,record:inv,reason:'Duplicate invoice number inside workbook'});continue}seenInvoices.add(inv);prepared.records.projects.push(made.project);prepared.records.invoices.push(made.invoice)}break}}
 if(!salesFound)prepared.warnings.push('No invoice register was found. Expense tables can still be imported.');parseExpenses(sheets,selection,prepared.source,prepared);return prepared;
}

function expenseFpExisting(row,type){return [type,text(row.Date||row['Document date']),norm(row.Supplier),round2(row.Gross).toFixed(2),round2(row['Invoice VAT']??row.VAT).toFixed(2),norm(row.Description)].join('|')}
function compare(prepared,canonical){
 const os=canonical?.os||{},bk=canonical?.bookkeeping||{},projectIds=new Set((os.projects||[]).map(p=>p.id)),projectKeys=new Set((os.projects||[]).map(p=>p.legacySourceKey||p.legacyImport?.key).filter(Boolean)),projectInvoices=new Set((os.projects||[]).map(p=>invoiceNumber(p.invoice?.number)).filter(Boolean)),invoiceKeys=new Set((bk.invoices||[]).map(r=>r._migrationKey).filter(Boolean)),invoiceNos=new Set((bk.invoices||[]).map(r=>invoiceNumber(r['Invoice #']||r.invoiceNumber)).filter(Boolean));
 const plan={projects:[],invoices:[],expenses:[],fuel:[],auto:[],skipped:{projects:0,invoices:0,expenses:0,fuel:0,auto:0}};
 for(const p of prepared.records.projects||[]){if(projectIds.has(p.id)||projectKeys.has(p.legacySourceKey)||projectInvoices.has(invoiceNumber(p.invoice?.number)))plan.skipped.projects++;else plan.projects.push(p)}
 for(const r of prepared.records.invoices||[]){if(invoiceKeys.has(r._migrationKey)||invoiceNos.has(invoiceNumber(r['Invoice #'])))plan.skipped.invoices++;else plan.invoices.push(r)}
 for(const [collection,type] of [['expenses','expenses'],['fuel','fuel'],['auto','auto']]){const existing=bk[collection]||[],keys=new Set(existing.map(r=>r._migrationKey).filter(Boolean)),counts=new Map();for(const r of existing){const fp=r['Legacy fingerprint']||r._legacyFingerprint||expenseFpExisting(r,type),n=(counts.get(fp)||0)+1;counts.set(fp,n)}for(const r of prepared.records[collection]||[]){const fp=r['Legacy fingerprint']||r._legacyFingerprint,occ=Number(r['Legacy occurrence']||r._legacyOccurrence)||1;if(keys.has(r._migrationKey)||(counts.get(fp)||0)>=occ)plan.skipped[collection]++;else plan[collection].push(r)}}return plan;
}
function totals(prepared){return Object.fromEntries(Object.entries(prepared.records||{}).map(([k,v])=>[k,(v||[]).length]))}
root.RenoweetLegacyXlsxEngine={VERSION,parseSheets,compare,totals,parseLegacyDate,parseInvoiceDate,invoiceNumber,expenseFingerprint,hash};
})(typeof window!=='undefined'?window:globalThis);
