'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),crypto=require('crypto');
const V=require('../renoweet-os-vat-engine-v1.js'),P=require('../renoweet-partial-invoice-engine.js'),C=require('../renoweet-invoice-closing.js');
const decode=s=>String(s||'').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
function surface(){
 const nodes=new Map(),fixed=['projectModal','modalTitle','modalMeta','projectTabs','projectTabContent','viewRoot','toast'];let controls=[];
 const create=id=>({id,value:'',checked:false,disabled:false,dataset:{},style:{},classList:{add(){},remove(){}},addEventListener(){},querySelectorAll(){return id==='projectTabContent'?controls:[]},querySelector(){return null},_html:'',get innerHTML(){return this._html},set innerHTML(html){this._html=html;if(id!=='projectTabContent')return;for(const n of controls)nodes.delete(n.id);controls=[];for(const m of html.matchAll(/<(input|select|textarea)\b([^>]*\bid="([^"]+)"[^>]*)>/g)){const n=create(m[3]),attrs=m[2];m[4]=m[1]==='input'?'':html.slice(m.index+m[0].length).split('</'+m[1]+'>')[0];n.disabled=/\bdisabled\b/.test(attrs);n.checked=/\bchecked\b/.test(attrs);n.value=decode(attrs.match(/\bvalue="([^"]*)"/)?.[1]||'');if(m[1]==='textarea')n.value=decode(m[4]);if(m[1]==='select'){const opts=[...(m[4]||'').matchAll(/<option\b([^>]*)>([^<]*)<\/option>/g)],selected=opts.find(o=>/selected/.test(o[1]))||opts[0];n.value=decode(selected?.[1].match(/value="([^"]*)"/)?.[1]||selected?.[2]||'')}nodes.set(n.id,n);controls.push(n)}}});
 fixed.forEach(id=>nodes.set(id,create(id)));
 return {document:{getElementById:id=>nodes.get(id)||null,querySelector:()=>null,querySelectorAll:()=>[],addEventListener(){}},nodes};
}
function app({closing=true,mixed=false}={}){
 const dom=surface(),storage={getItem:()=>null,setItem(){},removeItem(){}},ctx={console,Intl,Date,Map,Set,Uint8Array,URL,Blob,crypto:crypto.webcrypto,navigator:{userAgent:'test'},location:{origin:'https://example.test',protocol:'https:',hostname:'example.test'},localStorage:storage,sessionStorage:storage,document:dom.document,setTimeout:()=>0,clearTimeout(){},confirm:()=>true,alert:message=>{throw new Error(message)},RenoweetOSVat:V,RenoweetPartialInvoices:P,RenoweetCompany:{html:()=>''}};
 if(mixed){ctx.RenoweetPartialInvoices={...P};delete ctx.RenoweetPartialInvoices.finalWorkRows;delete ctx.RenoweetPartialInvoices.closingStatement}
 if(closing)ctx.RenoweetInvoiceClosing=C;ctx.window=ctx;vm.createContext(ctx);
 const html=fs.readFileSync(require.resolve('../Renoweet-OS-Drive-v2.2.html'),'utf8');const main=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('function blankProject()'));
 vm.runInContext(main.slice(main.indexOf('const HANDLE_DB='),main.indexOf('const pinActionBtn=')),ctx);
 vm.runInContext('scheduleSave=()=>{};render=()=>{};clearProjectDraftRecovery=()=>{};queueProjectDraftRecovery=()=>{};const fixture=blankProject();fixture.id="reopen";fixture.title="Test";fixture.customer.name="Customer";fixture.customer.address="Address";fixture.estimate=[{id:"low",desc:"Painting",qty:1,rate:1120,vatTreatment:"NL_LOW"},{id:"high",desc:"Floor",qty:1,rate:2430,vatTreatment:"NL_HIGH"}];db.projects=[fixture];',ctx);
 vm.runInContext(fs.readFileSync(require.resolve('../renoweet-partial-invoices-ui.js'),'utf8'),ctx);return {ctx,dom,project:vm.runInContext('fixture',ctx)};
}
const {ctx,dom,project}=app();ctx.openProject('reopen','intake');ctx.switchTab('invoice');ctx.newPartialInvoice();dom.nodes.get('partial_amount').value='2080.55';ctx.refreshPartialInvoice();ctx.sendToBookkeeping();const partial=JSON.stringify(project.invoiceDocuments[0]);
for(let i=0;i<4;i++){ctx.closeProject();ctx.openProject('reopen','intake');ctx.switchTab('invoice');assert(dom.nodes.get('projectTabContent').innerHTML.includes('DEELFACTUUR'));ctx.openInvoiceDocument(project.invoice.number);assert.equal(JSON.stringify(project.invoiceDocuments[0]),partial)}
ctx.prepareFinalInvoice();assert(dom.nodes.get('projectTabContent').innerHTML.includes('EINDFACTUUR'));dom.nodes.get('final_description_0').value='Completed painting';ctx.refreshPartialInvoice();ctx.sendToBookkeeping();const final=JSON.stringify(project.invoiceDocuments[1]);
for(let i=0;i<4;i++){ctx.closeProject();ctx.openProject('reopen','intake');ctx.switchTab('invoice');assert(dom.nodes.get('projectTabContent').innerHTML.includes('EINDFACTUUR'));ctx.openInvoiceDocument(project.invoiceDocuments[0].number);ctx.openInvoiceDocument(project.invoiceDocuments[1].number);assert.equal(JSON.stringify(project.invoiceDocuments[0]),partial);assert.equal(JSON.stringify(project.invoiceDocuments[1]),final)}
console.log('Actual intake → invoice navigation, closing/reopening, partial history and frozen final invoice passed.');
const missing=app({closing:false});missing.ctx.openProject('reopen','invoice');missing.ctx.newPartialInvoice();missing.dom.nodes.get('partial_amount').value='500';missing.ctx.refreshPartialInvoice();missing.ctx.sendToBookkeeping();missing.ctx.prepareFinalInvoice();
console.log('Invoice reopening with an unavailable closing-display asset passed.');
const mixed=app({closing:false,mixed:true});mixed.project.invoice=JSON.parse(JSON.stringify(project.invoice));mixed.project.invoiceDocuments=JSON.parse(JSON.stringify(project.invoiceDocuments));mixed.ctx.openProject('reopen','invoice');assert(mixed.dom.nodes.get('projectTabContent').innerHTML.includes('EINDFACTUUR'));mixed.ctx.closeProject();mixed.ctx.openProject('reopen','invoice');const preserved=JSON.stringify(mixed.project);assert.throws(()=>mixed.ctx.sendToBookkeeping(),/different app versions/);assert.equal(JSON.stringify(mixed.project),preserved);
const legacy=app();delete legacy.project.invoice;legacy.ctx.openProject('reopen','invoice');assert(legacy.dom.nodes.get('projectTabContent').innerHTML.includes('Factuuroverzicht'));legacy.ctx.closeProject();legacy.ctx.openProject('reopen','intake');legacy.ctx.switchTab('invoice');assert(legacy.dom.nodes.get('projectTabContent').innerHTML.includes('Factuuroverzicht'));
const paymentApp=app();paymentApp.ctx.openProject('reopen','invoice');paymentApp.ctx.newPartialInvoice();paymentApp.dom.nodes.get('partial_amount').value='500';paymentApp.dom.nodes.get('partial_paid').checked=true;paymentApp.dom.nodes.get('partial_paid_date').value='2026-10-01';paymentApp.ctx.refreshPartialInvoice();paymentApp.ctx.sendToBookkeeping();const preservedPaid=JSON.stringify(paymentApp.project.invoiceDocuments);paymentApp.project.payments.push({id:'paid',amount:500,date:'2026-10-01',status:'Received'});paymentApp.ctx.closeProject();paymentApp.ctx.openProject('reopen','invoice');assert.equal(JSON.stringify(paymentApp.project.invoiceDocuments),preservedPaid);assert.equal(paymentApp.project.payments.length,1);
console.log('Mixed cached scripts, legacy invoice settings and reopening after a recorded payment passed.');
