'use strict';
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const pages=['index.html','Renoweet-Project-Notebook.html','Renoweet-Bookkeeping-Drive-v2.2.html','Renoweet-OS-Drive-v2.2.html','Renoweet-BOD-Drive-v2.2.html','Renoweet-Legacy-XLSX-Import-v4.4.html'];
const missing=[];
for(const page of pages){
  const text=fs.readFileSync(path.join(root,page),'utf8');
  for(const match of text.matchAll(/(?:src|href)=["']([^"']+)["']/g)){
    const ref=match[1];
    if(/^(?:https?:|data:|#|mailto:|tel:)/.test(ref)||ref.includes('${'))continue;
    const clean=ref.replace(/[?#].*$/,'').replace(/^\.\//,'');
    if(clean&&!fs.existsSync(path.join(root,clean)))missing.push(`${page}: ${ref}`);
  }
}
if(missing.length)throw new Error(`Missing local assets:\n${missing.join('\n')}`);
const bookkeeping=fs.readFileSync(path.join(root,'Renoweet-Bookkeeping-Drive-v2.2.html'),'utf8');
if(bookkeeping.includes('new Date(dateStr+"T00:00:00")'))throw new Error('Bookkeeping still converts date-only values through local midnight.');
if(!bookkeeping.includes('Date.UTC(Number(m[1]),Number(m[2])-1,Number(m[3]))'))throw new Error('Bookkeeping is missing timezone-safe date-only conversion.');
for(const required of ['renoweet-accounting-engine-v4.4.js','renoweet-bookkeeping-v4.4.js','styles-accounting-v4.4.css'])if(!bookkeeping.includes(required))throw new Error(`Bookkeeping is missing ${required}`);
const bookkeepingUi=fs.readFileSync(path.join(root,'renoweet-bookkeeping-v4.4.js'),'utf8');
if(bookkeepingUi.includes('<img src="icons/icon.svg" alt="Renoweet">'))throw new Error('Invoice preview must not use the Hub app icon.');
if(!bookkeepingUi.includes("document.querySelector('header .brand img')"))throw new Error('Invoice preview is not connected to the established Renoweet invoice logo.');
for(const required of ['onclick="printInvoices()"','onclick="printExpenses()"','window.printInvoices=invoicePrintReport','window.printExpenses=expensePrintReport'])if(!bookkeepingUi.includes(required))throw new Error(`Bookkeeping print workflow is missing ${required}`);
for(const required of ['Accounting core 4.4.4','expInsuranceContribution','Insurance payment route','Still owed','Invoice totals, settlement and cash timing are separate','Only expenses dated in the selected quarter','A.receivables(data,p)','A.controls(data,new Date(),p)'])if(!bookkeepingUi.includes(required))throw new Error(`Bookkeeping v4.4.4 workflow is missing ${required}`);
for(const required of ['Taxable work','0% costs','Invoice total','Paid','Outstanding','How to read it','Quarter calculation','This is a count of checks to review, not a score'])if(!bookkeepingUi.includes(required))throw new Error(`Clear invoice or dashboard explanation is missing ${required}`);
for(const required of ['REVERSE_CHARGE_NL','BTW verlegd','Customer VAT ID','rubriek 1e'])if(!(bookkeepingUi+fs.readFileSync(path.join(root,'renoweet-accounting-engine-v4.4.js'),'utf8')).includes(required))throw new Error(`Bookkeeping reverse-charge workflow is missing ${required}`);
for(const required of ['paymentTimingReport','Payment timing explains the difference','Paid against ','Cash received in ','Why Paid and Cash received can differ','Edit payment date'])if(!(bookkeepingUi+fs.readFileSync(path.join(root,'renoweet-accounting-engine-v4.4.js'),'utf8')).includes(required))throw new Error(`Payment timing reconciliation is missing ${required}`);
for(const required of ['Payment cannot exceed the invoice balance','editV44Payment','removeV44Payment','removed entries remain in Control','st.outstanding>.009'])if(!bookkeepingUi.includes(required))throw new Error(`Payment correction control is missing ${required}`);
for(const required of ['paymentRepairPanel','repairV44PaidInvoice','syncInvoicePaymentStatus','date_mismatch','Payment date corrected from','This ledger is the source for Cash received in','Recovered from legacy Paid status','Paid label needs repair'])if(!(bookkeepingUi+fs.readFileSync(path.join(root,'renoweet-accounting-engine-v4.4.js'),'utf8')).includes(required))throw new Error(`Permanent payment reconciliation is missing ${required}`);
for(const required of ['Issued invoices incl. VAT','Net invoiced after credits','Credit ledger','Remove mistaken credit','removeV44Credit','Credit note cannot exceed the remaining invoice value','A credit reduces what the customer owes'])if(!bookkeepingUi.includes(required))throw new Error(`Credit-note transparency or correction control is missing ${required}`);
for(const required of ['thead{display:table-header-group}','counter(page)','Complete invoice register','Complete expense register'])if(!(bookkeeping+bookkeepingUi).includes(required))throw new Error(`Print report layout is missing ${required}`);
const osPage=fs.readFileSync(path.join(root,'Renoweet-OS-Drive-v2.2.html'),'utf8');
const osDrive=fs.readFileSync(path.join(root,'renoweet-os-drive-adapter-v3.6.js'),'utf8');
const bookkeepingDrive=fs.readFileSync(path.join(root,'renoweet-bookkeeping-drive-adapter-v3.7.js'),'utf8');
for(const required of ['normalizeRecoveredProject','restoreProjectRecoveryFile','Restore project file'])if(!(osPage+osDrive).includes(required))throw new Error(`OS project recovery is missing ${required}`);
for(const required of ['Import old quarterly XLSX','Open legacy importer','Renoweet-Legacy-XLSX-Import-v4.4.html'])if(!osDrive.includes(required))throw new Error(`OS legacy XLSX import is missing ${required}`);
const legacyImport=fs.readFileSync(path.join(root,'Renoweet-Legacy-XLSX-Import-v4.4.html'),'utf8');
for(const required of ['Choose the period before uploading','Download compatible JSON','Connect Drive and check duplicates','Import missing records','renoweet-legacy-xlsx-engine-v4.4.js'])if(!legacyImport.includes(required))throw new Error(`Legacy XLSX import workflow is missing ${required}`);
for(const required of ["if($('inv_number'))","p.invoice.date=$('inv_date').value","p.invoice.dueDays=+$('inv_due').value","if(!p.invoice.number)p.invoice.number=nextInvoice(p.invoice.date)"])if(!osPage.includes(required))throw new Error(`OS → Bookkeeping invoice handoff is missing ${required}`);
for(const required of ['q_vat_treatment','inv_vat_treatment','inv_customer_vat','Customer VAT ID','VAT treatment','Line items JSON','REVERSE_CHARGE_NL'])if(!osPage.includes(required))throw new Error(`OS reverse-charge invoice workflow is missing ${required}`);
for(const obsolete of ["if($('i_number'))","p.invoice.date=$('i_date').value","p.invoice.dueDays=+$('i_due').value"])if(osPage.includes(obsolete))throw new Error(`OS invoice form still uses obsolete field mapping ${obsolete}`);
for(const required of ['bookkeepingQueuedAt','allOSQueueRows','osPendingRows','OS invoices waiting to import'])if(!bookkeepingDrive.includes(required))throw new Error(`Bookkeeping queue verification is missing ${required}`);
if(!bookkeepingDrive.includes('Connect Drive to check OS invoices'))throw new Error('Bookkeeping must not report zero OS invoices before Drive has been checked.');
if(bookkeepingDrive.includes("sy.textContent='0 OS invoices waiting to import'"))throw new Error('Bookkeeping still shows an unverified zero before Drive connection.');

for(const required of ['openPeriodsForCorrection','b.onclick=()=>spec[2]()','The screen has been refreshed to the live Drive state','controlled correction workflow'])if(!bookkeepingDrive.includes(required))throw new Error(`Closed-quarter correction workflow is missing ${required}`);
for(const required of ['openCorrectionPeriods','prepareV44PaidDateRepair','affected accounting period is closed',"AccountingSchema='4.4.4'"])if(!bookkeepingUi.includes(required))throw new Error(`Paid-invoice correction workflow is missing ${required}`);
const driveCore=fs.readFileSync(path.join(root,'renoweet-drive-core-v3.0.js'),'utf8');
for(const required of ['recordDate(e.before),recordDate(e.record)','archiveHistory','manifestHistory'])if(!driveCore.includes(required))throw new Error(`Closed-period audit protection is missing ${required}`);
const hub=fs.readFileSync(path.join(root,'app.js'),'utf8');
const notebook=fs.readFileSync(path.join(root,'renoweet-project-notebook.js'),'utf8');
const bridge=fs.readFileSync(path.join(root,'renoweet-os-project-bridge-v1.js'),'utf8');
for(const required of ['./Renoweet-Project-Notebook.html','focus_project_notebook'])if(!hub.includes(required))throw new Error(`Hub notebook entry is missing ${required}`);
for(const required of ['createFromNotebook','osProjectId','projectCreated','MAX_PHOTOS = 10'])if(!notebook.includes(required))throw new Error(`Project Notebook integration is missing ${required}`);
for(const required of ['listOpenProjects','notebookSeedFromOs','syncFromNotebook','isEligibleOpenProject','contractBasisVersion'])if(!(notebook+bridge).includes(required))throw new Error(`Project Notebook OS lead workflow is missing ${required}`);
for(const required of ['Open OS-projecten','osProjectList','refreshOsProjectsBtn'])if(!fs.readFileSync(path.join(root,'Renoweet-Project-Notebook.html'),'utf8').includes(required))throw new Error(`Project Notebook OS selector UI is missing ${required}`);
for(const required of ['renoweet-os-local-cache-v1','project-created','cacheBrowserState(true)','scheduleSave()'])if(!(bridge+osPage).includes(required))throw new Error(`OS project bridge is missing ${required}`);
if(!osPage.includes('renoweet-os-project-bridge-v1.js'))throw new Error('Renoweet OS does not load the Project Notebook bridge.');
const bodPage=fs.readFileSync(path.join(root,'Renoweet-BOD-Drive-v2.2.html'),'utf8');
const bodDrive=fs.readFileSync(path.join(root,'renoweet-bod-drive-adapter-v2.js'),'utf8');
for(const required of ['renoweet-accounting-engine-v4.4.js','bookkeepingPayments','creditNotes','A.invoiceState(r,book.payments,book.creditNotes)','A.vatReport(book,period)','A.profitAndLoss(book,period)','invoiceOutstanding'])if(!bodPage.includes(required))throw new Error(`BOD ledger accounting integration is missing ${required}`);
for(const required of ['(bk.payments||[])','(bk.creditNotes||[])',"rows(wb,'Customer Payments')", "rows(wb,'Credit Notes')",'bookkeepingPayments'])if(!bodDrive.includes(required))throw new Error(`BOD Drive ledger import is missing ${required}`);
if(!fs.readFileSync(path.join(root,'service-worker.js'),'utf8').includes('renoweet-focus-hub-v4.4.4-25'))throw new Error('Service-worker cache version was not bumped for the Project Notebook integration.');
console.log('Static asset checks passed.');
